baseURL: /
languageCode: en-za
title: Remount R/O
theme: archie
permalinks:
  posts: /:year/:month/:filename/
copyright: Owen Valentine
pygmentsstyle: dracula
pygmentscodefences: true
pygmentscodefencesguesssyntax: true
paginate: 5
params:
  favicon: /favicon.png
  og_image: /favicon.png
  mode: toggle
  useCDN: false
  subtitle: I'll waste my time on lengthy projects so you can read about them and realize you're better off ignoring them, probably
  social:
    - name: GitHub
      icon: github
      url: https://github.com/chessmango
    - name: LinkedIn
      icon: linkedin
      url: https://www.linkedin.com/in/owenvalentine/
  sourceurl: https://github.com/chessmango/remount.ro
  giscus_repo: chessmango/remount.ro
  giscus_repo-id: MDEwOlJlcG9zaXRvcnkzNzExNDI1Mzg=
  giscus_category: Comments
  giscus_category-id: DIC_kwDOFh8vis4COwcC
  giscus_mapping: pathname
  giscus_enable-reactions: 1
  giscus_emit-metadata: 0
  giscus_input-position: top
  giscus_theme: preferred_color_scheme
  giscus_lang: en
  giscus_loading: lazy

menu:
  main:
    - name: /
      url: /
      weight: 1
    - name: posts
      url: /posts
      weight: 2
    - name: tags
      url: /tags
      weight: 3
    - name: about
      url: /about
      weight: 4
frontmatter:
  lastmod:
    - lastmod
