baseURL: /
languageCode: en-za
title: Remount R/O
theme: archie
permalinks:
  posts: /:year/:month/:filename/
copyright: Owen Valentine
pygmentsstyle: dracula
pygmentscodefences: true
pygmentscodefencesguesssyntax: true
paginate: 5
params:
  favicon: /favicon.png
  og_image: /favicon.png
  mode: toggle
  useCDN: false
  subtitle: I'll waste my time on lengthy projects so you can read about them and realize you're better off ignoring them, probably
  social:
    - name: GitHub
      icon: github
      url: https://github.com/chessmango
    - name: LinkedIn
      icon: linkedin
      url: https://www.linkedin.com/in/owenvalentine/
  sourceurl: https://github.com/chessmango/remount.ro
  utterances_repo: chessmango/remount.ro
  utterances_issueterm: pathname
  utterances_label: comment
  utterances_theme: preferred-color-scheme
menu:
  main:
    - name: /
      url: /
      weight: 1
    - name: posts
      url: /posts
      weight: 2
    - name: tags
      url: /tags
      weight: 3
    - name: about
      url: /about
      weight: 4
frontmatter:
  lastmod:
    - lastmod
