#baseURL: https://remount.ro
languageCode: en-za
title: Remount R/O
theme: archie
permalinks:
  posts: /:year/:month/:filename/
copyright: Owen Valentine
paginate: 5
params:
  mode: auto
  useCDN: false
  subtitle: I'll waste my time on lengthy projects so you can read about them and realize you're better off ignoring them, probably
  social:
    - name: GitHub
      icon: github
      url: https://github.com/chessmango
    - name: Twitter
      icon: twitter
      url: https://twitter.com/chessmango
    - name: LinkedIn
      icon: linkedin
      url: https://www.linkedin.com/in/owenvalentine/
  sourceurl: https://github.com/chessmango/remount.ro
menu:
  main:
    - name: /
      url: /
      weight: 1
    - name: posts
      url: /posts
      weight: 2
    - name: tags
      url: /tags
      weight: 3
    - name: about
      url: /about
      weight: 4
frontmatter:
  lastmod:
    - lastmod
